#!/bin/bash
source etc/vars


## Create CA Request 
openssl req -new -config $DIR/etc/ca/tlsCA.cnf -out $DIR/ca/tls-ca.csr -keyout $DIR/ca/tls-ca/private/tls-ca.key


## Create CA certificate
openssl ca -config $DIR/etc/ca/CA.cnf -in $DIR/ca/tls-ca.csr -out $DIR/ca/tls-ca.crt -extensions signing_ca_ext

## Create initial CRL
openssl ca -gencrl -config $DIR/etc/ca/tlsCA.cnf -out $DIR/crl/tls-ca.crl

##Create Bundle
cat $DIR/ca/tls-ca.crt $DIR/ca/root-ca.crt > $DIR/ca/tls-ca-chain.pem
