#!/bin/bash
source etc/vars

if [ $# -eq 0  ]
then
	echo "Usage: revoke-tls-cert [serial]"
	exit;
fi

#Revoke certificate

openssl ca -config $DIR/etc/ca/tlsCA.cnf  -revoke $DIR/ca/tls-ca/$1.pem -crl_reason keyCompromise
