#!/bin/bash
source etc/vars

if [ $# -eq 0  ]
then
	echo "Usage: sign-email-req [name]"
	exit;
fi

#Create email certificate
openssl ca -config $DIR/etc/ca/emailCA.cnf  -in certs/email/$1.csr  -out certs/email/$1.crt -extensions email_ext
